address: 0.0.0.0:8080

logger:
  log_level: debug      # Available Modes: trace, debug, info, warn, error, fatal, panic

kafka:
  bootstrap_servers:
    - "broker:9092"
  topic:
    order_event: order_event
