version: "3.9"

services:
  exchange_service:
    build:
      context: .
      args:
        - app_name=exchange-service
    image: exchange-service
    restart: on-failure
    depends_on:
      - broker
    volumes:
      - ./config/exchange-service/config.yaml:/srv/trading-service/config/config.yaml
    command:
      - run_trading_service

  order_service:
    build:
      context: .
      args:
        - app_name=order-service
    image: order-service
    restart: on-failure
    depends_on:
      - broker
      - exchange_service
    volumes:
      - ./config/order-service/config.yaml:/srv/trading-service/config/config.yaml
    ports:
      - "8080:8080"
    command:
      - run_trading_service

  # kafka related services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.2.1
    hostname: broker
    container_name: broker
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_ENABLE: "false"
