logger:
  log_level: debug      # Available Modes: trace, debug, info, warn, error, fatal, panic

kafka:
  bootstrap_servers:
    - "broker:9092"
  topic:
    order_event: order_event
  consumer:
    group_id: exchange_service
    enable_auto_commit: false
